language: node_js

node_js:
  - "11.0"

branches:
  only:
    - master

before_script:
  - npm install -g @vue/cli firebase-tools

script:
  - npm install
  - npm run build
  - cd functions && npm install

deploy:
  skip_cleanup: true
  provider: script
  script: firebase deploy --only hosting,storage,firestore --token $FIREBASE_TOKEN
  message: build $TRAVIS_BUILD_NUMBER $TRAVIS_BRANCH/$COMMIT_HASH
